//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WFTTNN.rc
//
#define IDD_FORM_READ_TERMINAL_INFO     9
#define IDD_ABOUTBOX                    100
#define IDD_WFTTNN_FORM                 101
#define IDR_MAINFRAME                   128
#define IDR_WFTTNNTYPE                  129
#define IDD_DIALOG_TERMINALPARENT       130
#define IDD_DIALOG_BAOWEN               131
#define IDD_DIALOG_TERMINALINFO         132
#define IDD_DIALOG_RNDREAD              133
#define IDD_DIALOG_DATABROWSE           134
#define IDI_ICON_ABOUT                  135
#define IDI_ICON_SET                    136
#define IDI_ICON_BROWSE                 137
#define IDI_ICON_EXIT                   138
#define IDI_ICON_TERM                   139
#define IDI_ICON_RNDREAD                140
#define IDD_DIALOG_SETPARAM             143
#define IDD_DIALOG_AUTOTEST             144
#define IDD_DIALOG_OPERATELOG           145
#define IDD_DIALOG_SETCHANNEL           146
#define IDI_ICON_CHANNELSET             147
#define IDI_ICON_AUTOCESHI              148
#define IDD_DIALOG_CONNECT              149
#define IDI_ICON_STOP                   150
#define IDI_ICON_CONN                   151
#define IDD_DIALOG_PEIZHI               152
#define IDD_DIALOG_BATCHINFO            153
#define IDD_DIALOG2                     154
#define IDD_DIALOG_AUTOTASK             155
#define IDD_FORM_READ_CURRENT_DATA      156
#define IDD_FORM_READ_HISTORY_DATA      157
#define IDI_ICON1                       157
#define IDI_ICON_FILE                   157
#define IDD_FORM_READ_EVENT_DATA        158
#define IDD_FORM_AUTO_TEST              159
#define IDR_MENU_CHECKLIST              159
#define IDD_FORM_OTHER_TEST             160
#define IDD_FORM_VISUAL_METER           161
#define IDD_FORM_TASK_MANAGE            162
#define IDD_TABPAGE_NOW                 164
#define IDD_TABPAGE_HISTORY             165
#define IDD_TABPAGE_EVENT               166
#define IDD_DIALOG1                     167
#define IDD_REPORT_VIEW                 167
#define IDR_RT_MANIFEST1                168
#define IDD_FORM_READ_EVENT_DATA1       168
#define IDD_FORM_READ_ALARM_DATA        168
#define IDD_FORM_TEST_REREAD            169
#define IDC_TREE_TERMINAL               1000
#define IDC_EDIT1                       1001
#define IDC_EDIT_TERMINALTIME           1001
#define IDC_EDIT_BEGINMETER             1001
#define IDC_EDTASKNAME                  1001
#define IDC_LIST_TERMINALINFO           1002
#define IDC_EDIT5                       1002
#define IDC_EDIT_SYSTEMTIME             1002
#define IDC_EDIT_ENDMETER               1002
#define IDC_EDIT_INSPECTUNIT            1002
#define IDC_TXT_INSPECTUNIT             1002
#define IDC_TXT_CSSZ                    1002
#define IDC_EDIT2                       1003
#define IDC_EDIT_TERMINALNAME           1003
#define IDC_EDIT_CHANNELNAME            1003
#define IDC_EDIT_VERSION                1003
#define IDC_EDIT_SUPPLYYEAR             1003
#define IDC_TXT_VOLTAGE                 1003
#define IDC_TXT_QXSJ                    1003
#define IDC_EDIT3                       1004
#define IDC_EDIT_TERMINALADDR           1004
#define IDC_EDIT_IP                     1004
#define IDC_EDIT_CHECKTYPE              1004
#define IDC_EDIT6                       1004
#define IDC_TXT_BARCODE                 1004
#define IDC_TXT_SUPPLYYEAR              1004
#define IDC_TXT_ELECTRICITY             1004
#define IDC_EDIT4                       1005
#define IDC_EDIT_TERMINALFACTORY        1005
#define IDC_EDIT_PORT                   1005
#define IDC_EDIT7                       1005
#define IDC_TXT_LID                     1005
#define IDC_BUTTON1                     1006
#define IDC_EDIT_PHONE                  1006
#define IDC_EDIT_ASSERTNO               1006
#define IDC_EDIT8                       1006
#define IDC_TXT_PEDESTAL                1006
#define IDC_BUTTON2                     1007
#define IDC_LIST_RNDREADINFO            1007
#define IDC_BUTTON_DELTERMINAL          1007
#define IDC_EDIT_CHAR                   1007
#define IDC_BUTTON_CANCEL               1007
#define IDC_BUTTON_DELBATCHINFO         1007
#define IDC_DELTASK                     1007
#define IDC_BTN_SEND                    1007
#define IDC_BTN_REPORT                  1007
#define IDC_EDIT9                       1007
#define IDC_BTN_SET                     1007
#define IDC_BTN_FROMTEMPLATE            1007
#define IDC_TXT_TERMADDR                1007
#define IDC_TXT_RSJ                     1007
#define IDC_BUTTON3                     1008
#define IDC_COMBO1                      1008
#define IDC_BUTTON_MODIFYTERMINAL       1008
#define IDC_BTN_SEND2                   1008
#define IDC_EDIT10                      1008
#define IDC_BTN_CALL                    1008
#define IDC_TXT_FACTORY                 1008
#define IDC_DATETIMEPICKER1             1009
#define IDC_COMBO2                      1009
#define IDC_BUTTON7                     1009
#define IDC_DATETIME_STARTDATE          1009
#define IDC_EDIT26                      1009
#define IDC_TXT_OUTNO                   1009
#define IDC_EDIT_ASSERTNO2              1009
#define IDC_EDIT_CJBH                   1009
#define IDC_DATETIMEPICKER2             1010
#define IDC_COMBO3                      1010
#define IDC_BUTTON8                     1010
#define IDC_DATETIME_STARTTIME          1010
#define IDC_BUTTON_METERDEL             1010
#define IDC_BUTTON_MODIFYCHANNEL        1010
#define IDC_EDIT27                      1010
#define IDC_CMB_LAMP                    1010
#define IDC_CMB_SUPPLY                  1010
#define IDC_DATETIMEPICKER3             1011
#define IDC_BUTTON9                     1011
#define IDC_BUTTON_METERSAVE            1011
#define IDC_BUTTON_SAVECHANNEL          1011
#define IDC_BUTTON_MODIFYBATCHINFO      1011
#define IDC_COMBO5                      1011
#define IDC_CMB_BARCODE                 1011
#define IDC_DATETIMEPICKER4             1012
#define IDC_COMBO_ENERGYTYPE            1012
#define IDC_COMBO_DATABIT               1012
#define IDC_COMBO6                      1012
#define IDC_CMB_LID                     1012
#define IDC_CMB_DM_FACTORY              1012
#define IDC_BUTTON4                     1013
#define IDC_DATETIMEPICKER5             1013
#define IDC_COMBO_TERMINALNO            1013
#define IDC_COMBO_STOPBIT               1013
#define IDC_BUTTON_TERMINALTIME         1013
#define IDC_ADDSTEP                     1013
#define IDC_BTN_OTHER_SAVE              1013
#define IDC_BUTTON5                     1014
#define IDC_DATETIMEPICKER6             1014
#define IDC_COMBO_CHECKWAY              1014
#define IDC_BUTTON_TERMINALVERSION      1014
#define IDC_COMBO7                      1014
#define IDC_CMB_PEDESTAL                1014
#define IDC_DELSTEP                     1015
#define IDC_COMBO8                      1015
#define IDC_CMB_NAMEPLATE               1015
#define IDC_BUTTON_READ                 1016
#define IDC_EDIT11                      1016
#define IDC_DATETIMEPICKER7             1016
#define IDC_TXT3                        1016
#define IDC_DTP_INSPECTDT               1016
#define IDC_DTP_INSPECTDT_START         1016
#define IDC_BUTTON_SEND                 1017
#define IDC_COMBO10                     1017
#define IDC_DATETIMEPICKER8             1017
#define IDC_CMB_SCREW                   1017
#define IDC_BUTTON_DEL                  1018
#define IDC_EDIT12                      1018
#define IDC_TXT2                        1018
#define IDC_EDIT13                      1019
#define IDC_TXT4                        1019
#define IDC_LIST_DATABROWSE             1020
#define IDC_EDIT14                      1020
#define IDC_TXT6                        1020
#define IDC_BUTTON_ADDTERMIANL          1021
#define IDC_EDIT15                      1021
#define IDC_TXT5                        1021
#define IDC_EDIT_TERMINALNO             1022
#define IDC_EDIT16                      1022
#define IDC_TXT9                        1022
#define IDC_COMBO4                      1023
#define IDC_COMBO_CURDATATYPE           1023
#define IDC_EDIT_TERMINALNO2            1023
#define IDC_EDIT17                      1023
#define IDC_TXT8                        1023
#define IDC_CMB_TERM_TYPE               1023
#define IDC_BUTTON6                     1024
#define IDC_BUTTON_CURDATA              1024
#define IDC_EDIT_TERM_NAME              1024
#define IDC_EDIT18                      1024
#define IDC_TXT11                       1024
#define IDC_LIST1                       1025
#define IDC_EDIT19                      1025
#define IDC_TXT12                       1025
#define IDC_LIST2                       1026
#define IDC_EDIT20                      1026
#define IDC_TXT13                       1026
#define IDC_LIST_DEVICE                 1026
#define IDC_LIST_DAY_DATAITEM           1026
#define IDC_LIST_DM_TERM                1026
#define IDC_LIST3                       1027
#define IDC_EDIT21                      1027
#define IDC_TXT14                       1027
#define IDC_LIST4                       1028
#define IDC_EDIT22                      1028
#define IDC_TXT10                       1028
#define IDC_CHECK1                      1029
#define IDC_EDIT23                      1029
#define IDC_CHECK_HARDVER               1029
#define IDC_TXT15                       1029
#define IDC_CHECK_SUPPLY                1029
#define IDC_CHECK2                      1030
#define IDC_EDIT24                      1030
#define IDC_CHECK_SOFTVER               1030
#define IDC_TXT16                       1030
#define IDC_CHECK3                      1031
#define IDC_COMBO9                      1031
#define IDC_CHECK_TIME                  1031
#define IDC_CMB_1                       1031
#define IDC_CMB_RESULT                  1031
#define IDC_CHECK4                      1032
#define IDC_CKREAL                      1032
#define IDC_COMBO11                     1032
#define IDC_CMB_2                       1032
#define IDC_CHECK_SYSTEMTIME            1032
#define IDC_LIST5                       1033
#define IDC_RESULT                      1033
#define IDC_LIST_REPORT                 1033
#define IDC_COMBO12                     1033
#define IDC_CMB_3                       1033
#define IDC_LIST_SETPARAMINFO           1034
#define IDC_COMBO13                     1034
#define IDC_CMB_4                       1034
#define IDC_LIST_OPERATEINFO            1035
#define IDC_COMBO14                     1035
#define IDC_CMB_5                       1035
#define IDC_COMBO_DATATYPE              1036
#define IDC_COMBO15                     1036
#define IDC_CMB_6                       1036
#define IDC_BUTTON_HISTORYDATA          1037
#define IDC_COMBO_DATATYPEHIS           1037
#define IDC_COMBO16                     1037
#define IDC_CMB_8                       1037
#define IDC_DATETIME_ENDDATE            1038
#define IDC_COMBO17                     1038
#define IDC_CMB_9                       1038
#define IDC_DATETIME_ENDTIME            1039
#define IDC_COMBO18                     1039
#define IDC_CMB10                       1039
#define IDC_EDIT_PACKETLOG              1040
#define IDC_COMBO19                     1040
#define IDC_CMB11                       1040
#define IDC_EDIT_METERNO                1041
#define IDC_COMBO20                     1041
#define IDC_CMB12                       1041
#define IDC_COMBO_METERTYPE             1042
#define IDC_COMBO21                     1042
#define IDC_CMB13                       1042
#define IDC_EDIT_METERADDR              1043
#define IDC_COMBO22                     1043
#define IDC_CMB14                       1043
#define IDC_COMBO_METERPROTOCOL         1044
#define IDC_COMBO23                     1044
#define IDC_CMB15                       1044
#define IDC_BUTTON_METERADD             1045
#define IDC_COMBO24                     1045
#define IDC_CMB16                       1045
#define IDC_BUTTON_METERMODIFY          1046
#define IDC_EDIT25                      1046
#define IDC_TXT7                        1046
#define IDC_EDIT_METERNAME              1047
#define IDC_LIST_SETCHANNELINFO         1047
#define IDC_COMBO25                     1047
#define IDC_CMB_7                       1047
#define IDC_EDIT_CHANNELID              1048
#define IDC_CMB_QXSJ                    1048
#define IDC_COMBO_CHANNELTYPE           1049
#define IDC_CMB_RSJ                     1049
#define IDC_COMBO_BAUD                  1050
#define IDC_CMB_YSJ                     1050
#define IDC_COMBO_SERIAL                1051
#define IDC_TXT_YSJ                     1051
#define IDC_BUTTON_ADDCHANNEL           1052
#define IDC_CMB_SJJL                    1052
#define IDC_BUTTON_DELCHANNEL           1053
#define IDC_TXT_SJJL                    1053
#define IDC_ADD                         1054
#define IDC_BUTTON_SYSTEMTIME           1054
#define IDC_CMB_GJJL                    1054
#define IDC_DEL                         1055
#define IDC_IPADDRESS                   1055
#define IDC_TXT_GJJL                    1055
#define IDC_START                       1056
#define IDC_COMBO_TERMINALTYPE          1056
#define IDC_CMB_ZDDS                    1056
#define IDC_LIST_TERMINALINFO1          1057
#define IDC_BUTTON_ADDBATCHINFO         1057
#define IDC_TXT_ZDDS                    1057
#define IDC_CKPARAM                     1058
#define IDC_EDIT_BATCHNO                1058
#define IDC_CMB_SJTC                    1058
#define IDC_CKTIME                      1059
#define IDC_EDIT34                      1059
#define IDC_TXT_SJTC                    1059
#define IDC_CKHIS                       1060
#define IDC_RADIO1                      1060
#define IDC_RADIO2                      1061
#define IDC_TYPE                        1061
#define IDC_RADIO3                      1062
#define IDC_ADDTASK                     1062
#define IDC_RADIO4                      1063
#define IDC_SAVESTEP                    1064
#define IDC_VIEWTASK                    1065
#define IDC_RDCUR                       1066
#define IDC_RDHIS                       1067
#define IDC_COMBO_BATCH_INFO            1068
#define IDC_LIST_OPT_RESULT             1070
#define IDC_LIST_DATAITEM               1071
#define IDC_BTN_START                   1072
#define IDC_TERMINAL                    1073
#define IDC_DATETIMEPICKER_START_DATE   1074
#define IDC_LIST_METER                  1074
#define IDC_DATETIMEPICKER_START_DATE2  1075
#define IDC_TXT_VERSION                 1075
#define IDC_BTN_STOP                    1075
#define IDC_TXT_VERSION1                1075
#define IDC_RRD_METER_LIST              1075
#define IDC_LABEL_TIPS                  1076
#define IDC_LIST_METER2                 1076
#define IDC_BTN_TEST                    1077
#define IDC_TXT_VERSION2                1077
#define IDC_LIST_TERMINAL               1078
#define IDC_RRD_BTN_STOP                1078
#define IDC_LIST_CHANNEL                1079
#define IDC_LIST_TASKS                  1080
#define IDC_BTN_TASK_MANAGE             1081
#define IDC_LBL_TERMINAL                1082
#define IDC_LBL_CHANNEL                 1083
#define IDC_LBL_TASK                    1084
#define IDC_LBL_REPORT                  1085
#define IDC_GROUP                       1086
#define IDC_TASKITEM                    1087
#define IDC_LIST_TASK                   1088
#define IDC_RECT                        1092
#define IDC_CMB_CHL_TYPE                1094
#define IDC_PROGRESS_REALTIME           1095
#define IDC_BTN_CONNECT                 1096
#define IDC_CMB_BAUD                    1097
#define IDC_CMB_CHECK                   1098
#define IDC_CMB_DATABIT                 1099
#define IDC_CMB_STOPBIT                 1100
#define IDC_SAVE                        1101
#define IDC_PROGRESS1                   1101
#define IDC_LIST_NOW                    1102
#define IDC_LIST_HISTORY                1103
#define IDC_BTN_DISCONNECT              1104
#define IDC_BTN_START1                  1105
#define IDC_TXT_TERMNO                  1106
#define IDC_TXT_TERMFACT                1107
#define IDC_TXT_TERMUNIT                1108
#define IDC_TXT_SSC                     1109
#define IDC_CMB_SSC                     1110
#define IDC_TXT_LAMP                    1111
#define IDC_TXT_NAMEPLATE               1112
#define IDC_TXT_SCREW                   1113
#define IDC_TXT1                        1114
#define IDC_LIST_TERM_DATAITEM          1115
#define IDC_BTN_START_READ              1116
#define IDC_EVENT_DATE_START            1117
#define IDC_EVENT_TIME_START            1118
#define IDC_EVENT_DATE_END              1119
#define IDC_EVENT_END_TIME              1120
#define IDC_BTN_TOTEMPLATE              1121
#define IDC_CMB_CHECKTYPE               1123
#define IDC_DATE_CHECK                  1124
#define IDC_DATE_                       1125
#define IDC_DATE_SUPPLY                 1125
#define IDC_LIST_BATCHINFO              1126
#define IDC_LIST_MON_DATAITEM           1127
#define IDC_EDIT_TERM                   1128
#define IDC_CMB_FACTORY                 1129
#define IDC_TXT_BATCHNO                 1130
#define IDC_BTN_SEARCH                  1131
#define IDC_LIST_ALARM_DEVICE           1132
#define IDC_LIST_ALARM_DATAITEM         1133
#define IDC_LIST_ALARM_TERM_DATAITEM    1134
#define IDC_LIST_OPT_ALARM_RESULT       1135
#define IDC_ALARM_DATE_START            1136
#define IDC_ALARM_TIME_START            1137
#define IDC_ALARM_DATE_END              1138
#define IDC_ALaRM_END_TIME              1139
#define IDC_BTN_START_ALARM_READ        1140
#define IDC_CMB_BC_SUPPLY               1141
#define IDC_STATIC_RESULT               1142
#define IDC_COMBO_RESULT                1143
#define IDC_BUTTON_RESULT               1144
#define IDC_BTN_EVENT_STOP              1145
#define IDC_BTN_ALARM_STOP              1146
#define IDC_BTN_DB_REPORT               1147
#define IDC_DTP_INSPECTDT_END           1148
#define IDC_CMB_SJZC                    1149
#define IDC_TXT_SJZC                    1150
#define IDC_CMB_CSSZ                    1151
#define IDC_CHECK5                      1152
#define IDC_CHECK_METERREADTIME         1152
#define IDC_CHECK6                      1153
#define IDC_CHECK_DATARESET             1153
#define IDC_EDIT_TERMINALMODEL          1154
#define IDC_CHECK7                      1155
#define IDC_CHECK_TERMINALRESET         1155
#define IDC_CHECK_ALARMNOSHIELD         1156
#define IDC_CHECK9                      1157
#define IDC_CHECK_EVENTNOSHIELD         1157
#define IDC_RRD_DATAITEM_LIST           1158
#define IDC_RRD_BTN_START               1160
#define IDC_RRD_RESULT_LIST             1161
#define IDC_RRD_TERMINAL                1162
#define IDC_CHECK_ZDSB_DISABLE          1163
#define IDC_BTN_CLEAR                   1164
#define IDC_CHECK_ZDCBCS                1165
#define IDC_CHECK_RS485_1               1166
#define IDC_CHECK_RS485_2               1167
#define IDC_CHECK_RS485_3               1168
#define IDC_CHECK_RS485_4               1169
#define IDC_CHECK_RS485_5               1170
#define IDC_CHECK_RS485_6               1171
#define IDC_CHECK_RS485_7               1172
#define IDC_CHECK_RS485_8               1173
#define ID_MENUITEM32771                32771
#define ID_MENUITEM_RNDREAD             32771
#define ID_MENUITEM_TERMINALINFO        32772
#define ID_MENUITEM_DATABROWSE          32773
#define ID_MENUITEM_EXIT                32774
#define ID_MENUITEM_YUANMAN             32775
#define ID_MENUITEM_SETCHANNEL          32777
#define ID_MENUITEM_SETPARAM            32778
#define ID_MENUITEM_AUTOCESHI           32779
#define ID_MENUITEM_CONNECT             32780
#define ID_MENUITEM_STOP                32781
#define ID_Menu32783                    32783
#define ID_Menu_Read_RealTimeData       32790
#define ID_Menu_Read_AlarmData          32793
#define ID_Menu_Read_ReadTermInfo       32794
#define ID_MENUITEM_METERINFO           32796
#define ID_MENUITEM_BATCHINFO           32797
#define ID_Menu_Read_HistoryData        32798
#define ID_MENUITEM_AUTOTEST            32801
#define ID_MENUITEM_TASK                32804
#define ID_32806                        32806
#define ID_MENUITEM_OTHERTEST           32807
#define ID_MENUITEM_VISUALMETER         32809
#define ID_Menu                         32810
#define ID_32811                        32811
#define ID_Menu32812                    32812
#define ID_32813                        32813
#define ID_MENUITEM_VIEW_TOOLBAR        32814
#define ID_MENUITEM_VIEW_TREE           32815
#define ID_MENUITEM_VIEW_OUTPUT         32816
#define ID_Menu32817                    32817
#define ID_MENU_32818                   32818
#define ID_MENU_32819                   32819
#define ID_MENU_                        32820
#define ID_MENUITEM_SELECTALL           32821
#define ID_MENUITEM_SELECT              32822
#define ID_MENUITEM_SELECTIVERT         32823
#define ID_MENUITEM_SELECTINVERT        32824
#define ID_Menu32825                    32825
#define ID_Menu_Read_EventData          32826
#define ID_32827                        32827
#define ID_MENU_TEST_REREAD             32828

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32829
#define _APS_NEXT_CONTROL_VALUE         1174
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
